import Foundation

enum ExerciseLibrarySeed {
    static func definitions() -> [ExerciseDefinition] {
        [
            ExerciseDefinition(
                id: SeedID.gobletSquat,
                name: "Goblet Squat",
                slug: "goblet-squat",
                category: .strength,
                primaryMuscleGroups: [.quads, .glutes],
                secondaryMuscleGroups: [.core],
                equipment: .dumbbell,
                setupInstructions: "Stand with feet about shoulder-width apart, toes slightly out. Hold one dumbbell vertically against your chest with both hands under the top head. Brace your trunk and keep your chest tall.",
                movementInstructions: "Sit your hips down and back until your thighs are at least parallel to the floor, keeping the dumbbell close to your chest. Drive through mid-foot to stand tall without bouncing at the bottom.",
                breathingCue: "Breathe in on the way down, breathe out as you stand.",
                coachingCues: [
                    "Keep elbows inside your knees at the bottom.",
                    "Heels stay planted.",
                    "Finish standing tall without hyperextending the low back.",
                    "Leave about 3–4 reps in reserve.",
                ],
                commonMistakes: [
                    "Letting the dumbbell drift forward and rounding the upper back.",
                    "Knees collapsing inward.",
                    "Cutting depth to chase heavier load.",
                ],
                localVideoName: "goblet-squat",
                defaultRestSeconds: 90
            ),
            ExerciseDefinition(
                id: SeedID.romanianDeadlift,
                name: "Dumbbell Romanian Deadlift",
                slug: "dumbbell-romanian-deadlift",
                category: .strength,
                primaryMuscleGroups: [.hamstrings, .glutes],
                secondaryMuscleGroups: [.back, .core],
                equipment: .dumbbell,
                setupInstructions: "Stand tall holding a dumbbell in each hand in front of your thighs, palms facing you. Soften the knees and brace your trunk.",
                movementInstructions: "Hinge at the hips, sending them back while the dumbbells travel close to your legs. Stop when you feel a strong hamstring stretch with a neutral spine, then squeeze the glutes to return to standing.",
                breathingCue: "Inhale as you hinge, exhale as you stand.",
                coachingCues: [
                    "Think hips back, not knees forward.",
                    "Keep the bar path — here, the dumbbells — close to your legs.",
                    "Maintain a long spine from head to tailbone.",
                    "Stop the set before form breaks.",
                ],
                commonMistakes: [
                    "Rounding the lower back to go lower.",
                    "Squatting the movement instead of hinging.",
                    "Letting the dumbbells drift away from the legs.",
                ],
                localVideoName: "dumbbell-romanian-deadlift",
                defaultRestSeconds: 90
            ),
            ExerciseDefinition(
                id: SeedID.chestPress,
                name: "Dumbbell Chest Press",
                slug: "dumbbell-chest-press",
                category: .strength,
                primaryMuscleGroups: [.chest],
                secondaryMuscleGroups: [.triceps, .shoulders],
                equipment: .dumbbell,
                setupInstructions: "Lie on a bench with feet planted. Hold a dumbbell in each hand above mid-chest, wrists stacked over elbows. Lightly retract the shoulder blades.",
                movementInstructions: "Lower the dumbbells with control until they are roughly beside mid-chest. Press them back up over the chest without clanging them together at the top.",
                breathingCue: "Inhale as you lower, exhale as you press.",
                coachingCues: [
                    "Keep shoulder blades gently set on the bench.",
                    "Wrists stay stacked over the dumbbells.",
                    "Do not bounce at the bottom.",
                    "Stop 3–4 reps before failure.",
                ],
                commonMistakes: [
                    "Flaring elbows extremely wide.",
                    "Arching the low back off the bench to grind extra reps.",
                    "Pressing toward the face instead of mid-chest.",
                ],
                localVideoName: "dumbbell-chest-press",
                defaultRestSeconds: 90
            ),
            ExerciseDefinition(
                id: SeedID.oneArmRow,
                name: "One-Arm Dumbbell Row",
                slug: "one-arm-dumbbell-row",
                category: .strength,
                primaryMuscleGroups: [.back, .lats],
                secondaryMuscleGroups: [.biceps, .core],
                equipment: .dumbbell,
                laterality: .unilateral,
                setupInstructions: "Place one hand and the same-side knee on a bench. The working-side foot is planted. Hold a dumbbell with a straight working arm, spine long and hips square.",
                movementInstructions: "Row the dumbbell toward your hip, leading with the elbow. Pause briefly, then lower with control. Complete the prescribed reps on one side before switching, or alternate sides if you prefer.",
                breathingCue: "Exhale as you row, inhale as you lower.",
                coachingCues: [
                    "Pull the elbow toward the hip, not out to the side.",
                    "Keep the torso from rotating.",
                    "The entered weight is the load in one hand.",
                    "Leave a few reps in reserve on each side.",
                ],
                commonMistakes: [
                    "Yank the weight with torso rotation.",
                    "Shrugging the shoulder to the ear.",
                    "Rounding the upper back.",
                ],
                localVideoName: "one-arm-dumbbell-row",
                defaultRestSeconds: 75
            ),
            ExerciseDefinition(
                id: SeedID.shoulderPress,
                name: "Dumbbell Shoulder Press",
                slug: "dumbbell-shoulder-press",
                category: .strength,
                primaryMuscleGroups: [.shoulders],
                secondaryMuscleGroups: [.triceps, .core],
                equipment: .dumbbell,
                setupInstructions: "Sit or stand tall with a dumbbell in each hand at shoulder height, palms facing forward or slightly in. Brace your trunk and keep ribs down.",
                movementInstructions: "Press the dumbbells overhead until the arms are long but not locked aggressively. Lower them back to the shoulders with control.",
                breathingCue: "Exhale as you press, inhale as you lower.",
                coachingCues: [
                    "Do not lean back to finish the press.",
                    "Keep the neck long; do not poke the chin forward.",
                    "Stop before the last grinders.",
                ],
                commonMistakes: [
                    "Excessive back arch.",
                    "Bouncing out of the bottom.",
                    "Pressing the bells far forward of the head.",
                ],
                localVideoName: "dumbbell-shoulder-press",
                defaultRestSeconds: 90
            ),
            ExerciseDefinition(
                id: SeedID.latPulldown,
                name: "Lat Pulldown",
                slug: "lat-pulldown",
                category: .strength,
                primaryMuscleGroups: [.lats, .back],
                secondaryMuscleGroups: [.biceps],
                equipment: .machine,
                setupInstructions: "Sit with thighs secured under the pad. Take a comfortable overhand grip slightly wider than shoulders. Sit tall with a slight lean back.",
                movementInstructions: "Pull the bar to the upper chest by driving the elbows down and back. Control the return until the arms are long without losing your seated posture.",
                breathingCue: "Exhale as you pull, inhale as you return.",
                coachingCues: [
                    "Think elbows into back pockets.",
                    "Keep the chest open.",
                    "This exercise is optional if the gym has no machine.",
                ],
                commonMistakes: [
                    "Yanking the bar behind the neck.",
                    "Using excessive body English.",
                    "Shrugging instead of depressing the shoulders.",
                ],
                localVideoName: "lat-pulldown",
                defaultRestSeconds: 90,
                notes: "Skip if the gym does not have a pulldown machine."
            ),
            ExerciseDefinition(
                id: SeedID.plank,
                name: "Plank",
                slug: "plank",
                category: .strength,
                primaryMuscleGroups: [.core],
                secondaryMuscleGroups: [.shoulders],
                equipment: .bodyweight,
                setupInstructions: "Place forearms on the floor, elbows under shoulders. Legs extended, feet hip-width. Create a straight line from head to heels.",
                movementInstructions: "Hold the position without letting the hips sag or pike. Breathe steadily. End the set when you can no longer keep a long, quiet position.",
                breathingCue: "Breathe steadily; do not hold your breath.",
                coachingCues: [
                    "Squeeze glutes lightly and brace as if expecting a tap on the stomach.",
                    "Keep the neck in line with the spine.",
                    "Target 20–30 seconds to start.",
                ],
                commonMistakes: [
                    "Hips sagging toward the floor.",
                    "Holding the breath.",
                    "Shrugging the shoulders toward the ears.",
                ],
                localVideoName: "plank",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultRestSeconds: 60,
                defaultDurationSeconds: 25,
                trackingMode: .duration
            ),
            ExerciseDefinition(
                id: SeedID.indoorCycling,
                name: "Indoor Cycling",
                slug: "indoor-cycling",
                category: .cardio,
                primaryMuscleGroups: [.cardio, .quads],
                equipment: .bike,
                setupInstructions: "Set saddle height so the knee is slightly bent at the bottom of the stroke. Keep a relaxed upper body.",
                movementInstructions: "Ride at a conversational pace. You should be able to speak in short sentences. Adjust resistance rather than sprinting.",
                breathingCue: "Breathe through the nose and mouth as needed; stay conversational.",
                coachingCues: [
                    "Easy cardio: 30–40 minutes.",
                    "If you cannot talk, ease off.",
                ],
                commonMistakes: [
                    "Treating an easy day as an interval session.",
                    "Saddle height too high or too low.",
                ],
                localVideoName: "indoor-cycling",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultSetCount: 1,
                defaultRestSeconds: 0,
                defaultDurationSeconds: 2100,
                trackingMode: .distanceDuration
            ),
            ExerciseDefinition(
                id: SeedID.treadmillWalking,
                name: "Treadmill Walking",
                slug: "treadmill-walking",
                category: .cardio,
                primaryMuscleGroups: [.cardio],
                equipment: .treadmill,
                setupInstructions: "Start at a comfortable walking speed. Use a light incline if that feels better on the joints than speeding up.",
                movementInstructions: "Walk at a pace where you can hold a conversation. Stand tall and let the arms swing naturally.",
                breathingCue: "Keep breathing easy and rhythmic.",
                coachingCues: [
                    "Conversational intensity.",
                    "30–40 minutes is enough.",
                ],
                commonMistakes: [
                    "Holding the handrails and leaning back.",
                    "Turning an easy walk into a hard run.",
                ],
                localVideoName: "treadmill-walking",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultSetCount: 1,
                defaultRestSeconds: 0,
                defaultDurationSeconds: 2100,
                trackingMode: .distanceDuration
            ),
            ExerciseDefinition(
                id: SeedID.walking,
                name: "Walking",
                slug: "walking",
                category: .cardio,
                primaryMuscleGroups: [.cardio],
                equipment: .none,
                setupInstructions: "Wear comfortable shoes. You do not need a formal warm-up for easy walking.",
                movementInstructions: "Walk outdoors or indoors at an easy pace. Use this for recovery or optional Saturday activity.",
                breathingCue: "Nasal breathing is fine if it feels comfortable.",
                coachingCues: [
                    "Easy and sustainable.",
                    "This can replace a gym session on recovery days.",
                ],
                commonMistakes: [
                    "Turning every walk into a hard effort.",
                ],
                localVideoName: "walking",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultSetCount: 1,
                defaultRestSeconds: 0,
                defaultDurationSeconds: 1800,
                trackingMode: .distanceDuration
            ),
            ExerciseDefinition(
                id: SeedID.swimming,
                name: "Swimming",
                slug: "swimming",
                category: .swimming,
                primaryMuscleGroups: [.cardio, .fullBody],
                equipment: .pool,
                setupInstructions: "Use a lane or quiet area of the pool. A 25 m pool is the app default; change pool length in Settings if needed.",
                movementInstructions: "Swim continuously or with easy rest between lengths. Record laps and time. Do not assume a watch is capturing the session.",
                breathingCue: "Breathe to the side on a comfortable pattern; never force breath-holds.",
                coachingCues: [
                    "About 30 minutes is the seeded target.",
                    "Enter laps manually if Health has no swim data.",
                ],
                commonMistakes: [
                    "Skipping rest when stroke quality is falling apart.",
                ],
                localVideoName: "swimming",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultSetCount: 1,
                defaultRestSeconds: 0,
                defaultDurationSeconds: 1800,
                trackingMode: .lapsDuration
            ),
            ExerciseDefinition(
                id: SeedID.mobility,
                name: "Mobility",
                slug: "mobility",
                category: .mobility,
                primaryMuscleGroups: [.fullBody],
                equipment: .none,
                setupInstructions: "Use a clear space. Move slowly. Stop any movement that causes sharp pain.",
                movementInstructions: "Work through easy hip, shoulder, and thoracic movements. This is recovery, not a flexibility test.",
                breathingCue: "Slow nasal breathing if comfortable.",
                coachingCues: [
                    "Optional on Wednesday recovery days.",
                    "Keep the session short and easy.",
                ],
                commonMistakes: [
                    "Forcing end ranges.",
                ],
                localVideoName: "mobility",
                defaultMinReps: 0,
                defaultMaxReps: 0,
                defaultSetCount: 1,
                defaultRestSeconds: 0,
                defaultDurationSeconds: 1200,
                trackingMode: .duration
            ),
        ]
    }
}
